<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--Define constants-->
  <xacro:property name="link_type" value="cuboidal" />
  <xacro:property name="PI" value="3.14159"/>
  <xacro:property name="mass1" value="50" />
  <xacro:property name="mass2" value="10" />
  <xacro:property name="mass3" value="5" />
  <xacro:property name="base_length" value="0.2" />
  <xacro:property name="base_radius" value="0.3" />
  
  <xacro:property name="link1_length" value="1.0" />
  <xacro:property name="link1_width" value="0.1" />

  <xacro:property name="link2_length" value="0.3" />
  <xacro:property name="link2_width" value="0.1" />

  <xacro:property name="link3_length" value="0.1" />
  <xacro:property name="link3_radius" value="0.05" />


  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="base_link" />
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
      <mass value="${mass1}"/>
      <inertia
        ixx="${mass1 / 12.0 * (2*base_radius*2*base_radius + base_length*base_length)}" ixy="0.0" ixz="0.0"
        iyy="${mass1 / 12.0 * (base_length*base_length + 2*base_radius*2*base_radius)}" iyz="0.0"
        izz="${mass1 / 12.0 * (2*base_radius*2*base_radius + 2*base_radius*2*base_radius)}"/>
    </inertial>
  </link>

  <link name="link_1">
    <visual>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${link1_width} ${link1_width} ${link1_length}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${link1_width} ${link1_width} ${link1_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
        ixx="${mass2 / 12.0 * (link1_width*link1_width + link1_length*link1_length)}" ixy="0.0" ixz="0.0"
        iyy="${mass2 / 12.0 * (link1_length*link1_length + link1_width*link1_width)}" iyz="0.0"
        izz="${mass2 / 12.0 * (link1_width*link1_width + link1_width*link1_width)}"/>
    </inertial>
  </link>

  <joint name="joint_1" type="continuous">
    <parent link="base_link"/>
    <child link="link_1"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${base_length}" rpy="0 0 0"/>
    <limit effort="30" velocity="1.0"/>
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" />
  </joint>


  <link name="link_2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${link2_width} ${link2_length} ${link2_width}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${link2_width}  ${link2_length} ${link2_width}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass3}"/>
      <inertia
        ixx="${mass2 / 12.0 * (link2_width*link2_width + link2_length*link2_length)}" ixy="0.0" ixz="0.0"
        iyy="${mass2 / 12.0 * (link2_width*link2_width + link2_width*link2_width)}" iyz="0.0"
        izz="${mass2 / 12.0 * (link2_length*link2_length + link2_width*link2_width)}"/>
    </inertial>
  </link>

  <joint name="joint_2" type="continuous">
    <parent link="link_1"/>
    <child link="link_2"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${link1_length+link2_width/2}" rpy="0 0 0"/>
    <limit effort="30" velocity="1.0"/>
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" />
  </joint>

  <link name="link_3">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link3_length}" radius="${link3_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link3_length}" radius="${link3_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass3}"/>
      <inertia
        ixx="${mass3 / 12.0 * (2*link3_radius*2*link3_radius + link3_length*link3_length)}" ixy="0.0" ixz="0.0"
        iyy="${mass3 / 12.0 * (link3_length*link3_length + 2*link3_radius*2*link3_radius)}" iyz="0.0"
        izz="${mass3 / 12.0 * (2*link3_radius*2*link3_radius + 2*link3_radius*2*link3_radius)}"/>
    </inertial>
  </link>

  <joint name="joint_3" type="continuous">
    <parent link="link_2"/>
    <child link="link_3"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0 ${link2_length/2+link3_radius} 0" rpy="0 0 0"/>
    <limit effort="30" velocity="1.0"/>
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-2.0" soft_upper_limit="0.5" />
  </joint>


</robot>